//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VELDDev.AvaloniaDSL
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "axaml";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"AvaloniaDSL";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"VELD-Dev";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID AvaloniaDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(AvaloniaCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID AvaloniaExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(AvaloniaCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewAvaloniaExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(AvaloniaCommandSetId), 0x0001);
	
		// Package identifier
		public const string AvaloniaPackageId = "fa635a4a-e87f-4f3f-9a43-80320b8afd22";
		
		// Editor factory identifier
		public const string AvaloniaEditorFactoryId = "08f825ea-7672-4d83-8742-cbcc92123e86";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string AvaloniaModelExplorerToolWindowId = "1e142df1-d3c8-48ba-b092-20bbb4c3c522";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace VELDDev.AvaloniaDSL
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string AvaloniaCommandSetId = "8e5f0312-9e3d-4e4e-86eb-fee084ac655f";
	}
}